March 08, 2016 - 22:50:15
Django version 1.9, using settings 'pollsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[08/Mar/2016 22:50:15] "GET / HTTP/1.1" 200 46
Performing system checks...

System check identified no issues (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

March 08, 2016 - 22:50:49
Django version 1.9, using settings 'pollsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[08/Mar/2016 22:50:52] "GET / HTTP/1.1" 200 46
Performing system checks...

System check identified no issues (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

March 08, 2016 - 22:51:03
Django version 1.9, using settings 'pollsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /
Traceback (most recent call last):
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/pollproject/poll_site/views.py", line 16, in hello_world_render
    return render(request, 'poll_site/index.html')
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/loader.py", line 43, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: poll_site/index.html
[08/Mar/2016 22:51:05] "GET / HTTP/1.1" 500 81290
Performing system checks...

System check identified no issues (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

March 08, 2016 - 22:51:13
Django version 1.9, using settings 'pollsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

March 08, 2016 - 22:51:17
Django version 1.9, using settings 'pollsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

March 08, 2016 - 22:51:25
Django version 1.9, using settings 'pollsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /
Traceback (most recent call last):
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/pollproject/poll_site/views.py", line 16, in hello_world_render
    return render(request, 'poll_site/index.html')
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/loader.py", line 43, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: poll_site/index.html
[08/Mar/2016 22:51:28] "GET / HTTP/1.1" 500 81290
Performing system checks...

System check identified no issues (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

March 08, 2016 - 22:52:27
Django version 1.9, using settings 'pollsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[08/Mar/2016 22:52:28] "GET / HTTP/1.1" 200 46
Performing system checks...

System check identified no issues (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

March 08, 2016 - 22:52:55
Django version 1.9, using settings 'pollsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /
Traceback (most recent call last):
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/pollproject/poll_site/views.py", line 16, in hello_world_render
    return render(request, 'poll_site/index.html')
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/loader.py", line 43, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: poll_site/index.html
[08/Mar/2016 22:52:57] "GET / HTTP/1.1" 500 81290
Internal Server Error: /
Traceback (most recent call last):
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/pollproject/poll_site/views.py", line 16, in hello_world_render
    return render(request, 'poll_site/index.html')
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/loader.py", line 43, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: poll_site/index.html
[08/Mar/2016 22:53:46] "GET / HTTP/1.1" 500 81290
Internal Server Error: /
Traceback (most recent call last):
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/pollproject/poll_site/views.py", line 16, in hello_world_render
    return render(request, 'poll_site/index.html')
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/loader.py", line 43, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: poll_site/index.html
[08/Mar/2016 22:53:48] "GET / HTTP/1.1" 500 81290
Internal Server Error: /
Traceback (most recent call last):
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/pollproject/poll_site/views.py", line 16, in hello_world_render
    return render(request, 'poll_site/index.html')
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/loader.py", line 43, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: poll_site/index.html
[08/Mar/2016 22:53:57] "GET / HTTP/1.1" 500 81290
Internal Server Error: /
Traceback (most recent call last):
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/pollproject/poll_site/views.py", line 16, in hello_world_render
    return render(request, 'poll_site/index.html')
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/loader.py", line 43, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: poll_site/index.html
[08/Mar/2016 22:55:12] "GET / HTTP/1.1" 500 81290
Internal Server Error: /
Traceback (most recent call last):
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/pollproject/poll_site/views.py", line 16, in hello_world_render
    return render(request, 'poll_site/index.html')
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/loader.py", line 43, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: poll_site/index.html
[08/Mar/2016 22:55:56] "GET / HTTP/1.1" 500 81267
Not Found: /favicon.ico
[08/Mar/2016 22:55:57] "GET /favicon.ico HTTP/1.1" 404 2040
Performing system checks...

System check identified no issues (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

March 08, 2016 - 22:56:41
Django version 1.9, using settings 'pollsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[08/Mar/2016 22:56:44] "GET / HTTP/1.1" 200 146
Performing system checks...

System check identified no issues (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

March 08, 2016 - 22:57:14
Django version 1.9, using settings 'pollsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[08/Mar/2016 23:06:15] "GET / HTTP/1.1" 200 212
Not Found: /poll_site/stle.css
[08/Mar/2016 23:06:15] "GET /poll_site/stle.css HTTP/1.1" 404 2061
[08/Mar/2016 23:06:40] "GET / HTTP/1.1" 200 219
[08/Mar/2016 23:06:40] "GET /static/poll_site/stle.css HTTP/1.1" 404 1667
[08/Mar/2016 23:06:52] "GET / HTTP/1.1" 200 218
[08/Mar/2016 23:06:53] "GET /static/poll_site/stle.css HTTP/1.1" 404 1667
[08/Mar/2016 23:07:16] "GET / HTTP/1.1" 200 219
[08/Mar/2016 23:07:16] "GET /static/poll_site/style.css HTTP/1.1" 200 135
[08/Mar/2016 23:07:16] "GET /static/poll_site/stars.jpg HTTP/1.1" 404 1670
[08/Mar/2016 23:08:33] "GET / HTTP/1.1" 200 219
[08/Mar/2016 23:08:33] "GET /static/poll_site/style.css HTTP/1.1" 304 0
[08/Mar/2016 23:08:34] "GET /static/poll_site/stars.jpg HTTP/1.1" 200 7333
[08/Mar/2016 23:09:57] "GET / HTTP/1.1" 200 219
[08/Mar/2016 23:09:57] "GET /static/poll_site/style.css HTTP/1.1" 200 160
[08/Mar/2016 23:09:57] "GET /static/poll_site/stars.jpg HTTP/1.1" 304 0
[08/Mar/2016 23:10:17] "GET / HTTP/1.1" 200 219
[08/Mar/2016 23:10:17] "GET /static/poll_site/style.css HTTP/1.1" 200 165
[08/Mar/2016 23:10:17] "GET /static/poll_site/stars.jpg HTTP/1.1" 304 0
[08/Mar/2016 23:18:04] "GET / HTTP/1.1" 200 254
[08/Mar/2016 23:18:04] "GET /static/poll_site/style.css HTTP/1.1" 200 239
[08/Mar/2016 23:18:04] "GET /static/poll_site/stars.jpg HTTP/1.1" 304 0
[08/Mar/2016 23:21:53] "GET / HTTP/1.1" 200 254
[08/Mar/2016 23:21:53] "GET /static/poll_site/style.css HTTP/1.1" 200 236
[08/Mar/2016 23:21:53] "GET /static/poll_site/stars.jpg HTTP/1.1" 304 0
[08/Mar/2016 23:22:23] "GET / HTTP/1.1" 200 254
[08/Mar/2016 23:22:23] "GET /static/poll_site/style.css HTTP/1.1" 200 238
[08/Mar/2016 23:22:23] "GET /static/poll_site/stars.jpg HTTP/1.1" 304 0
[08/Mar/2016 23:22:25] "GET / HTTP/1.1" 200 254
[08/Mar/2016 23:22:25] "GET /static/poll_site/style.css HTTP/1.1" 304 0
[08/Mar/2016 23:22:25] "GET /static/poll_site/stars.jpg HTTP/1.1" 304 0
[08/Mar/2016 23:22:31] "GET / HTTP/1.1" 200 254
[08/Mar/2016 23:22:31] "GET /static/poll_site/style.css HTTP/1.1" 200 238
[08/Mar/2016 23:22:31] "GET /static/poll_site/stars.jpg HTTP/1.1" 304 0
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f22a09fc268>
Traceback (most recent call last):
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/checks/urls.py", line 10, in check_url_config
    return check_resolver(resolver)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/checks/urls.py", line 19, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/pollproject/pollsite/urls.py", line 20, in <module>
    from poll_site.views import *
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/pollproject/poll_site/views.py", line 19
    }
    ^
SyntaxError: invalid syntax
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fcc0a39b268>
Traceback (most recent call last):
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/checks/urls.py", line 10, in check_url_config
    return check_resolver(resolver)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/checks/urls.py", line 19, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/pollproject/pollsite/urls.py", line 20, in <module>
    from poll_site.views import *
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/pollproject/poll_site/views.py", line 16
    context = {'name': "Tiffany", 'fav_color' "Orange"} #pased to template index.html
                                                      ^
SyntaxError: invalid syntax
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f65641c1268>
Traceback (most recent call last):
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/checks/urls.py", line 10, in check_url_config
    return check_resolver(resolver)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/checks/urls.py", line 19, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/pollproject/pollsite/urls.py", line 20, in <module>
    from poll_site.views import *
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/pollproject/poll_site/views.py", line 16
    context = {'name': "Tiffany", 'fav_color' "Orange"} #pased to template index.html
                                                      ^
SyntaxError: invalid syntax
Performing system checks...

System check identified no issues (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

March 08, 2016 - 23:28:16
Django version 1.9, using settings 'pollsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[08/Mar/2016 23:28:17] "GET / HTTP/1.1" 200 268
[08/Mar/2016 23:28:17] "GET /static/poll_site/style.css HTTP/1.1" 200 238
[08/Mar/2016 23:28:17] "GET /static/poll_site/stars.jpg HTTP/1.1" 200 7333
Performing system checks...

System check identified no issues (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

March 08, 2016 - 23:28:56
Django version 1.9, using settings 'pollsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[08/Mar/2016 23:28:57] "GET / HTTP/1.1" 200 274
[08/Mar/2016 23:28:57] "GET /static/poll_site/style.css HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

March 08, 2016 - 23:33:38
Django version 1.9, using settings 'pollsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /
Traceback (most recent call last):
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/base.py", line 506, in parse
    compile_func = self.tags[command]
KeyError: 'end'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/pollproject/poll_site/views.py", line 18, in hello_world_render
    return render(request, 'poll_site/index.html', context)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/base.py", line 230, in compile_nodelist
    return parser.parse()
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
    raise self.error(token, e)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/base.py", line 512, in parse
    compiled_result = compile_func(self, token)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/defaulttags.py", line 886, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/base.py", line 508, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/shawnwaldow/Documents/CodeSchool/Week1/django/poll_site/lib/python3.4/site-packages/django/template/base.py", line 562, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until]),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 27: 'end', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
[08/Mar/2016 23:33:39] "GET / HTTP/1.1" 500 144140
Performing system checks...

System check identified no issues (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

March 08, 2016 - 23:33:51
Django version 1.9, using settings 'pollsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

March 08, 2016 - 23:34:32
Django version 1.9, using settings 'pollsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[08/Mar/2016 23:34:48] "GET / HTTP/1.1" 200 396
[08/Mar/2016 23:34:48] "GET /static/poll_site/style.css HTTP/1.1" 304 0
[08/Mar/2016 23:35:46] "GET / HTTP/1.1" 200 396
[08/Mar/2016 23:35:46] "GET /static/poll_site/style.css HTTP/1.1" 200 264
[08/Mar/2016 23:35:46] "GET /static/poll_site/stars.jpg HTTP/1.1" 304 0
[08/Mar/2016 23:36:30] "GET / HTTP/1.1" 200 403
[08/Mar/2016 23:36:30] "GET /static/poll_site/style.css HTTP/1.1" 304 0
[08/Mar/2016 23:36:47] "GET / HTTP/1.1" 200 414
[08/Mar/2016 23:36:47] "GET /static/poll_site/style.css HTTP/1.1" 304 0
[08/Mar/2016 23:36:58] "GET / HTTP/1.1" 200 413
[08/Mar/2016 23:36:59] "GET /static/poll_site/style.css HTTP/1.1" 304 0
[08/Mar/2016 23:37:31] "GET / HTTP/1.1" 200 419
[08/Mar/2016 23:37:31] "GET /static/poll_site/style.css HTTP/1.1" 304 0
[08/Mar/2016 23:37:41] "GET / HTTP/1.1" 200 419
[08/Mar/2016 23:37:41] "GET /static/poll_site/style.css HTTP/1.1" 304 0
[08/Mar/2016 23:37:54] "GET / HTTP/1.1" 200 414
[08/Mar/2016 23:37:55] "GET /static/poll_site/style.css HTTP/1.1" 304 0
^C(poll_site) shawnwaldow@shawnwaldow-K53E:~/Documents/CodeSchool/Week1/django/pollproject$ deactivate
shawnwaldow@shawnwaldow-K53E:~/Documents/CodeSchool/Week1/django/pollproject$ 
